# Generated by Django 5.0.2 on 2024-02-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.CharField(default='title', max_length=128),
            preserve_default=False,
        ),
    ]
